### PR TITLE
Add list of feats.

### PR DESCRIPTION
**Pull request by CuriousCactus**

### CODE REVIEW

**Comment by prophet-kn** [comment]
I have a feeling it will output the descriptions as strings, that's why in spells list it is full of <br> tags.

**Comment by CuriousCactus** [comment]
I've made a rendered list of feats with filters now, but this is waiting on #30 for how to implement it properly.

**Comment by CuriousCactus** [comment]
I've had a go at re-implementing this, let me know what you think :)

**Comment by prophet-kn** [comment]
Overall looks very good! I especially like the regex for url querying, especially useful when more items come into play, such as the Monster List I am also working on currently.

There are these visual changes (code-wise) and variable names that I am having problem with, makes it difficult for me to see which file I am currently looking at.

I will know more once I pull and do actual test on it, this is just from looking at the code.

But nice! :D
-kn

**Comment by CuriousCactus** [comment]
Variable name changes now made :)

**Comment by prophet-kn** [comment]
I gotta fix a few tiny things, but looks good, thanks!

**Pull request merged**
