### PR TITLE
Feature/pc 28 tashas feats

### PR DESCRIPTION
**Pull request by CuriousCactus**
- Add new feats
- Add sorting on the ability score
- Remove Guiding Hand, Hand of Radiance, Healing Elixir, Puppet, Sense Emotion, Sudden Awakening, Unearthly Chorus, Virtue and Wild Cunning as they are only in UA.

### CODE REVIEW

**Comment by prophet-kn** [comment]
@CuriousCactus 
`Remove Guiding Hand, Hand of Radiance, Healing Elixir, Puppet, Sense Emotion, Sudden Awakening, Unearthly Chorus, Virtue and Wild Cunning as they are only in UA.`

why? think they are too OP and due to being only in UA not entirely tested?

**Comment by CuriousCactus** [comment]
They were UA a while ago and deliberately not included in Xanathar's. I'm not opposed to putting UA in the app, but it should be clearly marked, because I've accidentally assumed that spell was official in two campaigns now before I realised :sweat_smile:

**Comment by prophet-kn** [comment]
Well... if I have to live in a world without an Elf Warlock abusing short-rest rules for spell slots and preloading with Healing Elixirs, I am all the better for it. :P There's some pipeline error though, I'll hopefully check it today or tomorrow :)

**Comment by prophet-kn** [comment]
yay, nice, merg'd

**Pull request merged**
